version: "3.9"
   
services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  production:
    build: .
    command: uwsgi --http "0.0.0.0:8800" --module lilisSchool.wsgi --master --processes 4 --threads 2
    volumes:
      - .:/code
    ports:
      - "8800:8800"
