# Generated by Django 3.2.7 on 2021-09-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeadLine', models.TextField(max_length=100)),
                ('Text', models.TextField(max_length=2000)),
                ('Bild', models.ImageField(upload_to='pictures/')),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FotosVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Beschreibung', models.TextField(max_length=2000)),
                ('Bild', models.ImageField(upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='WilkommensText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(max_length=2000)),
                ('Anzeigen', models.BooleanField(default=True)),
            ],
        ),
    ]
