# Generated by Django 3.2.7 on 2021-09-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_sponsoren'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Beschreibung', models.TextField(max_length=2000)),
                ('Headline', models.CharField(max_length=50)),
                ('Jahr', models.IntegerField()),
            ],
        ),
    ]
