# Generated by Django 3.2.7 on 2021-09-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_roadmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paypal', models.URLField()),
                ('Instagram', models.URLField()),
                ('Facebook', models.URLField()),
                ('Youtube', models.URLField()),
            ],
        ),
    ]
