# Generated by Django 3.2.7 on 2021-09-13 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210912_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='TimeToRead',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wilkommenstext',
            name='Bild',
            field=models.ImageField(default='pictures/wir.jpg', upload_to='pictures/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wilkommenstext',
            name='HeadLine',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wilkommenstext',
            name='SmallHeadLine',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
