# Generated by Django 3.2.7 on 2021-09-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210913_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wilkommenstext',
            name='HeadLine',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wilkommenstext',
            name='SmallHeadLine',
            field=models.TextField(max_length=100),
        ),
    ]
