# Generated by Django 3.2.7 on 2021-09-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210913_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='Aktuell',
            field=models.BooleanField(default=True),
        ),
    ]
