# Generated by Django 3.2.7 on 2021-09-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_kontakt_aktuell'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
