# Generated by Django 3.2.7 on 2021-09-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_blog_timetoread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Bild',
        ),
        migrations.AddField(
            model_name='blog',
            name='Bild1',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='Bild2',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
    ]
